### PR TITLE
update to hapi 8, bump other dependencies

### LINKED ISSUE #57: Update to hapi 8

### PR DESCRIPTION
**Pull request by nlf**
Closes #57

### CODE REVIEW

**Comment by wraithgar** [comment]
This will constitute a major version bump because of non-backwards compatibility in the global context handler

**Comment by evilpacket** [comment]
+1 ocular grep.

**Comment by evilpacket** [comment]
@adambrault can we get a merge? so we can move the lift blog to hapi 8 and out of unsupported territory?

**Comment by adambrault** [comment]
@evilpacket I'm deferring to @wraithgar

**Comment by wraithgar** [comment]
Welcome to bumble 3.0.0

**Pull request merged**
